// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 3);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 175);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[]},\"seen\":[\"reset-pbm-toolbar-button\"],\"dirtyAreaCache\":[],\"currentVersion\":24,\"newElementCount\":0}");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "a3074b26-cd15-4a76-9179-b68730a09379");
user_pref("datareporting.dau.cachedUsageProfileID", "1699a6ec-e858-4498-b0c7-f96a099c5f29");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "153.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260722113846");
user_pref("extensions.lastAppVersion", "153.0");
user_pref("extensions.lastPlatformVersion", "153.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"352d4647-4dd3-47f8-ab31-b7ea81ba2be5\",\"ipp-activator@mozilla.com\":\"068578c4-6c8a-44ca-b3d8-cc770e91b3e8\",\"pictureinpicture@mozilla.org\":\"9fd42feb-8f6d-46c2-b3e5-73a7cd9a7782\",\"addons-search-detection@mozilla.com\":\"ee566273-56ca-44d1-bc7d-8d8385c424b0\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"e6f08035-7dac-4af5-804b-6b4b76495f7f\",\"default-theme@mozilla.org\":\"e79acb15-5539-4672-a588-21cc9ad62ecf\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "8ad5af47-e718-4d95-83bb-11e69296c129");
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.startup.last_success", 1786844716);
user_pref("toolkit.telemetry.cachedClientID", "e71a168d-83b2-4e78-a27e-e3cb8c6a2afb");
user_pref("toolkit.telemetry.cachedProfileGroupID", "0c52d8a2-9008-4ea0-9d22-9635ad1686de");
user_pref("toolkit.telemetry.previousBuildID", "20260722113846");
